language: node_js
cache: npm
node_js:
  - 14
before_script:
  - npm install -g gatsby-cli yarn
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: main
